#!/bin/bash
cd /var/www/phplaravel
yum -y update
yum install php73.x86_64 ea-php73-php-intl.x86_64

yum install php73.x86_64 ea-php73-php-soap.x86_64

yum install php73.x86_64 ea-php73-php-zip.x86_64
curl -s https://getcomposer.org/installer | php
php composer.phar install
mv composer.phar /usr/local/bin/composer
sed -i "s|AllowOverride None|AllowOverride All|g"  /etc/httpd/conf/httpd.conf
sed -i "s|/var/www/html|/var/www/phplaravel/public|g"  /etc/httpd/conf/httpd.conf
chown -R ec2-user:ec2-user /var/www/phplaravel
userAdd -G ec2-user apache
chgrp -R apache storage bootstrap/cache
chmod -R ug+rwx storage bootstrap/cache

# Create cache and chmod folders
mkdir -p /var/www/phplaravel/bootstrap/cache
mkdir -p /var/www/phplaravel/storage/framework/sessions
mkdir -p /var/www/phplaravel/storage/framework/views
mkdir -p /var/www/phplaravel/storage/framework/cache
mkdir -p /var/www/phplaravel/public/files/

# Install dependencies
export COMPOSER_ALLOW_SUPERUSER=1
composer install -d /var/www/phplaravel/

# Copy configuration from /var/www/.env, see README.MD for more information
cp /var/www/.env /var/www/phplaravel/.env

# Migrate all tables
php /var/www/phplaravel/artisan migrate

# Clear any previous cached views
php /var/www/phplaravel/artisan config:clear
php /var/www/phplaravel/artisan cache:clear
php /var/www/phplaravel/artisan view:clear

# Optimize the application
php /var/www/phplaravel/artisan config:cache
php /var/www/phplaravel/artisan optimize
#php /var/www/phplaravel/artisan route:cache

# Change rights
chmod 777 -R /var/www/phplaravel/bootstrap/cache
chmod 777 -R /var/www/phplaravel/storage
chmod 777 -R /var/www/phplaravel/public/files/

# Bring up application
php /var/www/phplaravel/artisan up
